#!/usr/bin/node
import { runProxmoxDesktopDriverCliV1 } from "/usr/local/lib/nelos-provider-driver/src/proxmox-desktop-test-driver.mjs";

runProxmoxDesktopDriverCliV1().catch(() => { process.exitCode = 1; });
